{
	"projectsettings": {
		"version": "Version 2-alpha",
		"versionnum": "2.0.0-alpha",
		"initialversionnum": "2-alpha",
		"projectid": "g_V2alpha",
		"name": "GS2 Test Project",
		"upm": 1000,
		"ascent": 700,
		"descent": -300,
		"capheight": 675,
		"xheight": 400,
		"linegap": 250,
		"italicangle": 0,
		"griddivisions": 10,
		"overshoot": 10,
		"defaultlsb": 20,
		"defaultrsb": 20,
		"glyphrange": {
			"basiclatin": true,
			"latinsuppliment": false,
			"latinextendeda": false,
			"latinextendedb": false,
			"custom": [],
			"filternoncharpoints": true
		},
		"pointsize": 7,
		"spinnervaluechange": 1,
		"renderpointssnappedtogrid": true,
		"combineshapesonexport": false,
		"maxcombineshapesonexport": 30,
		"showkeyboardtipsicon": true,
		"stoppagenavigation": true,
		"formatsavefile": true,
		"showoutline": false,
		"showfill": true,
		"snaptogrid": false,
		"snaptoguides": false,
		"colors": {
			"glyphfill": "rgb(0,0,0)",
			"glyphoutline": "rgb(0,0,0)",
			"gridlightness": 96,
			"guide_dark": "rgb(204,81,0)",
			"guide_med": "rgb(255,132,51)",
			"guide_light": "rgb(255,193,153)"
		}
	},
	"metadata": {
		"shared": "{{sectionbreak}}",
		"font_family": "GS2 Test Project",
		"font_style": "normal",
		"panose_1": "2 0 0 0 0 0 0 0 0 0",
		"otf": "{{sectionbreak}}",
		"designer": "\"\"",
		"designerURL": "\"\"",
		"manufacturer": "\"\"",
		"manufacturerURL": "\"\"",
		"license": "\"\"",
		"licenseURL": "\"\"",
		"version": "\"\"",
		"description": "\"\"",
		"copyright": "\"\"",
		"trademark": "\"\"",
		"svg": "{{sectionbreak}}",
		"font_variant": "normal",
		"font_weight": 400,
		"font_stretch": "normal",
		"stemv": "\"\"",
		"stemh": "\"\"",
		"slope": "\"\"",
		"underline_position": -50,
		"underline_thickness": 10,
		"strikethrough_position": 300,
		"strikethrough_thickness": 10,
		"overline_position": 750,
		"overline_thickness": 10
	},
	"glyphs": {
		"0x0041": {
			"objtype": "glyph",
			"name": "Latin Capital Letter A",
			"glyphhtml": "&#65;",
			"isautowide": true,
			"leftsidebearing": false,
			"rightsidebearing": false,
			"ratiolock": false,
			"usedin": [],
			children: [
				"Path",{"applyMatrix":true,"segments":[[[54,125],[-102,99],[102,-99]],[[294,37],[-70,-151],[70,151]],[[227,189],[223,-38],[-223,38]]],"closed":true,"fillColor":["hsb",236.36061,1,1,0.5]}
				],
		}
	},
	"components": {}
}